services:
  handle_server:
    container_name: handle_server
    image: public.ecr.aws/dissco/handle-server:latest
    network_mode: "host"
    restart: always
    volumes:
      - type: bind
        source: ${SRC_KEYS}/admpriv.bin
        target: ${TGT_KEYS}/admpriv.bin
      - type: bind
        source: ${SRC_KEYS}/privkey.bin
        target: ${TGT_KEYS}/privkey.bin
      - type: bind
        source: ${SRC_KEYS}/config.dct
        target: ${TGT_KEYS}/config.dct
      - type: bind
        source: ${SRC_KEYS}/serverCertificate.pem
        target: ${TGT_KEYS}/serverCertificate.pem
      - type: bind
        source: ${SRC_KEYS}/siteinfo.json
        target: ${TGT_KEYS}/siteinfo.json
      - type: bind
        source: ${SRC_KEYS}/sitebndl.zip
        target: ${TGT_KEYS}/sitebndl.zip
